try:
	print('Testing')
# except ValueError as err:
except Exception as err:
	print('Terjadi Kesalahan')
finally:
	print('finally')